### ISSUE TITLE
[Request] Add download button for videos

### ISSUE THREAD

**Issue by pakoito** [iUltimateLP/NXGallery#18]
I use Firefox for Windows and the default player doesn't have a dedicated button to download videos. I can rightclick-download just right, I just thought it'd be nice for the UX to be consistent with pictures.

Otherwise this is a great hb, good job!

**Comment by iUltimateLP** [comment]
Hey, thanks! I wonder what do you mean? When opening a video, there's the download button under it right there:
![image](https://user-images.githubusercontent.com/8491339/154913461-67f62e9c-5fca-49b6-a00d-c17e3d20ed04.png)

**Comment by pakoito** [comment]
Oh, I never got to that screen. When I click on a video, it automatically plays.

**Comment by pakoito** [comment]
I didn't look for it bit I believe you.
